const ideaListData = [
  {
    createDate: "12 Dec 2022",
    ideaId: 1,
    userId: 5,
    ideaProfileImgURL: null,
    ideaName: "Community app",
    oneLinerDesr: "Helping ideas to grow from 0 to 1 through a community",
    descr:
      "A community of people helping each other to develop their ideas through providing comments, opinions, connections to build the idea into an actual business as the end goal",
    purpose:
      "Helping people to grow in their ideas through crowd sourced information and connection and cultivating a community of potential entrepreneurs",
    differentator: "",
    mainFeature: "",
    otherFeature: "",
    targetAud: "",
    usageReason: "",
    imgURL: null,
    videoURL: null,
    tag1: "Social Media",
    tag2: "Technology",
    tag3: null,
    status: "Live",
    numberFollowers: 20,
  },
  {
    date: "01 Jul 2021",
    userId: 5,
    ideaId: 2,
    ideaProfileImgURL: null,
    ideaName: "Toy with human interaction",
    oneLinerDesr: "Making your favourite toy a true companion",
    descr:
      "A community of people helping each other to develop their ideas through providing comments, opinions, connections to build the idea into an actual business as the end goal",
    purpose:
      "Helping people to grow in their ideas through crowd sourced information and connection and cultivating a community of potential entrepreneurs",
    differentator: "",
    mainFeature: "",
    otherFeature: "",
    targetAud: "",
    usageReason: "",
    imgURL: null,
    videoURL: null,
    numberFollowers: 4,
    tag1: "Toys",
    tag2: null,
    tag3: null,
    status: "Private",
    numberFollowers: null,
  },
  {
    date: "18 May 2021",
    userId: 5,
    ideaId: 3,
    ideaProfileImgURL: null,
    ideaName: "Toy with human interaction",
    oneLinerDesr: "Making your favourite toy a true companion",
    descr:
      "A community of people helping each other to develop their ideas through providing comments, opinions, connections to build the idea into an actual business as the end goal",
    purpose:
      "Helping people to grow in their ideas through crowd sourced information and connection and cultivating a community of potential entrepreneurs",
    differentator: "",
    mainFeature: "",
    otherFeature: "",
    targetAud: "",
    usageReason: "",
    imgURL: null,
    videoURL: null,
    numberFollowers: 4,
    tag1: "Toys",
    tag2: null,
    tag3: null,
    status: "Private",
    numberFollowers: null,
  },
];

export { ideaListData };
